"""World-frame X2 hybrid state construction used by D1 and later runtime code."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

import numpy as np

from .contract import DEFAULT_CONTRACT


class StateValidationError(ValueError):
  """A world state is malformed or contains non-finite values."""


def _array(
  name: str,
  value: np.ndarray | Iterable[float],
  shape: tuple[int, ...],
  *,
  batched: bool = False,
) -> np.ndarray:
  result = np.asarray(value, dtype=np.float64)
  valid = result.shape == shape or (
    batched and result.ndim == len(shape) + 1 and result.shape[1:] == shape
  )
  if not valid:
    raise StateValidationError(f"{name} must have shape {shape}, got {result.shape}")
  if not np.isfinite(result).all():
    raise StateValidationError(f"{name} contains non-finite values")
  return result


def _quat_matrix(quaternion: np.ndarray) -> np.ndarray:
  q = quaternion / np.linalg.norm(quaternion, axis=-1, keepdims=True)
  w, x, y, z = np.moveaxis(q, -1, 0)
  return np.stack(
    (
      1 - 2 * (y * y + z * z),
      2 * (x * y - z * w),
      2 * (x * z + y * w),
      2 * (x * y + z * w),
      1 - 2 * (x * x + z * z),
      2 * (y * z - x * w),
      2 * (x * z - y * w),
      2 * (y * z + x * w),
      1 - 2 * (x * x + y * y),
    ),
    axis=-1,
  ).reshape(*q.shape[:-1], 3, 3)


def _yaw_matrix(yaw: np.ndarray) -> np.ndarray:
  c, s = np.cos(yaw), np.sin(yaw)
  return np.stack(
    (
      c,
      -s,
      np.zeros_like(c),
      s,
      c,
      np.zeros_like(c),
      np.zeros_like(c),
      np.zeros_like(c),
      np.ones_like(c),
    ),
    axis=-1,
  ).reshape(*yaw.shape, 3, 3)


def _matrix_to_quaternion(matrix: np.ndarray) -> np.ndarray:
  """Convert proper rotation matrices to wxyz quaternions, vectorized."""
  # The state uses rotations generated by the matching forward transform, so
  # this stable diagonal-branch implementation is sufficient and avoids scipy.
  out = np.empty((*matrix.shape[:-2], 4), dtype=np.float64)
  trace = np.trace(matrix, axis1=-2, axis2=-1)
  positive = trace > 0.0
  s = np.sqrt(np.maximum(trace[positive] + 1.0, 1e-15)) * 2
  out[positive, 0] = 0.25 * s
  out[positive, 1] = (matrix[positive, 2, 1] - matrix[positive, 1, 2]) / s
  out[positive, 2] = (matrix[positive, 0, 2] - matrix[positive, 2, 0]) / s
  out[positive, 3] = (matrix[positive, 1, 0] - matrix[positive, 0, 1]) / s
  for index, (a, b, c) in enumerate(((0, 1, 2), (1, 0, 2), (2, 0, 1)), start=1):
    mask = ~positive & (
      np.diagonal(matrix, axis1=-2, axis2=-1)[..., index - 1]
      > np.diagonal(matrix, axis1=-2, axis2=-1)[..., (index) % 3]
    )
    if index == 3:
      mask = ~positive & ~(
        (
          np.diagonal(matrix, axis1=-2, axis2=-1)[..., 0]
          > np.diagonal(matrix, axis1=-2, axis2=-1)[..., 1]
        )
        | False
      )
    # A generic eigen-free fallback for rare near-180-degree rotations.
    if np.any(mask):
      d = (
        np.sqrt(
          np.maximum(
            1 + matrix[mask, a, a] - matrix[mask, b, b] - matrix[mask, c, c], 1e-15
          )
        )
        * 2
      )
      out[mask, index] = 0.25 * d
      out[mask, 0] = (matrix[mask, c, b] - matrix[mask, b, c]) / d
      out[mask, b] = (matrix[mask, b, a] + matrix[mask, a, b]) / d
      out[mask, c] = (matrix[mask, c, a] + matrix[mask, a, c]) / d
  # The branches above overlap only in numerical tie cases; normalize and use
  # the positive scalar convention for deterministic serialization.
  out /= np.linalg.norm(out, axis=-1, keepdims=True)
  out *= np.where(out[..., :1] < 0, -1.0, 1.0)
  return out


def _rot6d(matrix: np.ndarray) -> np.ndarray:
  return np.concatenate((matrix[..., :, 0], matrix[..., :, 1]), axis=-1)


def _rot6d_matrix(value: np.ndarray) -> np.ndarray:
  first, second = value[..., :3], value[..., 3:6]
  # The six values came from an orthonormal matrix.  Gram-Schmidt also makes
  # inverse transforms robust to a model prediction slightly off-manifold.
  first = first / np.linalg.norm(first, axis=-1, keepdims=True)
  second = second - np.sum(first * second, axis=-1, keepdims=True) * first
  second = second / np.linalg.norm(second, axis=-1, keepdims=True)
  third = np.cross(first, second)
  return np.stack((first, second, third), axis=-1)


@dataclass(frozen=True, slots=True)
class WorldState:
  """One simulator-ground-truth state in world coordinates."""

  root_position: np.ndarray
  root_quaternion_wxyz: np.ndarray
  root_linear_velocity: np.ndarray
  root_angular_velocity: np.ndarray
  body_positions: np.ndarray
  body_linear_velocities: np.ndarray

  def __post_init__(self) -> None:
    body_count = DEFAULT_CONTRACT.body_count
    object.__setattr__(
      self,
      "root_position",
      _array("root_position", self.root_position, (3,), batched=True),
    )
    object.__setattr__(
      self,
      "root_quaternion_wxyz",
      _array("root_quaternion_wxyz", self.root_quaternion_wxyz, (4,), batched=True),
    )
    object.__setattr__(
      self,
      "root_linear_velocity",
      _array("root_linear_velocity", self.root_linear_velocity, (3,), batched=True),
    )
    object.__setattr__(
      self,
      "root_angular_velocity",
      _array("root_angular_velocity", self.root_angular_velocity, (3,), batched=True),
    )
    object.__setattr__(
      self,
      "body_positions",
      _array("body_positions", self.body_positions, (body_count, 3), batched=True),
    )
    object.__setattr__(
      self,
      "body_linear_velocities",
      _array(
        "body_linear_velocities",
        self.body_linear_velocities,
        (body_count, 3),
        batched=True,
      ),
    )
    quaternion_norms = np.linalg.norm(
      self.root_quaternion_wxyz,
      axis=-1,
    )
    if np.any(quaternion_norms < 1e-12):
      raise StateValidationError("root quaternion has zero norm")

  @classmethod
  def stack(cls, states: Iterable["WorldState"]) -> "WorldState":
    values = tuple(states)
    if not values:
      raise StateValidationError("cannot stack an empty state sequence")
    return cls(
      *(
        np.stack([getattr(state, field) for state in values])
        for field in (
          "root_position",
          "root_quaternion_wxyz",
          "root_linear_velocity",
          "root_angular_velocity",
          "body_positions",
          "body_linear_velocities",
        )
      )
    )

  @property
  def count(self) -> int:
    return self.root_position.shape[0] if self.root_position.ndim == 2 else 1


@dataclass(frozen=True, slots=True)
class WorldFrameContext:
  """World values retained so a hybrid state can be inverted for physical costs."""

  center_position: np.ndarray
  center_yaw: float
  center_linear_velocity: np.ndarray
  root_positions: np.ndarray
  root_linear_velocities: np.ndarray
  root_yaws: np.ndarray


def _as_sequence(states: WorldState) -> tuple[np.ndarray, ...]:
  if states.root_position.ndim != 2:
    return tuple(
      np.expand_dims(getattr(states, field), 0)
      for field in (
        "root_position",
        "root_quaternion_wxyz",
        "root_linear_velocity",
        "root_angular_velocity",
        "body_positions",
        "body_linear_velocities",
      )
    )
  return tuple(
    getattr(states, field)
    for field in (
      "root_position",
      "root_quaternion_wxyz",
      "root_linear_velocity",
      "root_angular_velocity",
      "body_positions",
      "body_linear_velocities",
    )
  )


def world_to_hybrid(
  states: WorldState, *, center_index: int
) -> tuple[np.ndarray, WorldFrameContext]:
  """Pack a trajectory into the contract's 135-D pelvis-rooted hybrid state."""
  root_p, root_q, root_v, root_w, body_p, body_v = _as_sequence(states)
  n = root_p.shape[0]
  if center_index < 0 or center_index >= n:
    raise StateValidationError("center_index is outside the trajectory")
  root_r = _quat_matrix(root_q)
  yaw = np.arctan2(root_r[:, 1, 0], root_r[:, 0, 0])
  center_yaw = float(yaw[center_index])
  center_r = _yaw_matrix(np.asarray(center_yaw))
  center_rt = center_r.T
  root_rel_p = (root_p - root_p[center_index]) @ center_r
  root_rel_v = (root_v - root_v[center_index]) @ center_r
  root_rel_r = np.einsum("ij,njk->nik", center_rt, root_r)
  root_rel_w = root_w @ center_r
  body_rt = np.swapaxes(_yaw_matrix(yaw), -1, -2)
  body_rel_p = np.einsum("nij,nkj->nki", body_rt, body_p - root_p[:, None, :])
  body_rel_v = np.einsum("nij,nkj->nki", body_rt, body_v - root_v[:, None, :])
  hybrid = np.concatenate(
    (
      root_rel_p,
      _rot6d(root_rel_r),
      root_rel_v,
      root_rel_w,
      body_rel_p.reshape(n, -1),
      body_rel_v.reshape(n, -1),
    ),
    axis=-1,
  )
  context = WorldFrameContext(
    root_p[center_index].copy(),
    center_yaw,
    root_v[center_index].copy(),
    root_p.copy(),
    root_v.copy(),
    yaw.copy(),
  )
  return hybrid, context


def hybrid_to_world(hybrid: np.ndarray, context: WorldFrameContext) -> WorldState:
  """Invert :func:`world_to_hybrid` using retained world planning context."""
  value = np.asarray(hybrid, dtype=np.float64)
  if value.ndim != 2 or value.shape[1] != DEFAULT_CONTRACT.state_dimension:
    raise StateValidationError("hybrid must have shape [T, 135]")
  n = value.shape[0]
  if context.root_positions.shape != (n, 3) or context.root_linear_velocities.shape != (
    n,
    3,
  ):
    raise StateValidationError("world context does not match hybrid length")
  center_r = _yaw_matrix(np.asarray(context.center_yaw))
  root_r = np.einsum("ij,njk->nik", center_r, _rot6d_matrix(value[:, 3:9]))
  root_p = context.center_position + value[:, :3] @ center_r.T
  root_v = context.center_linear_velocity + value[:, 9:12] @ center_r.T
  root_w = value[:, 12:15] @ center_r.T
  body = value[:, 15:75].reshape(n, DEFAULT_CONTRACT.body_count, 3)
  body_v = value[:, 75:].reshape(n, DEFAULT_CONTRACT.body_count, 3)
  body_r = _yaw_matrix(context.root_yaws)
  body_p = root_p[:, None, :] + np.einsum("nij,nkj->nki", body_r, body)
  body_world_v = root_v[:, None, :] + np.einsum("nij,nkj->nki", body_r, body_v)
  return WorldState(
    root_p, _matrix_to_quaternion(root_r), root_v, root_w, body_p, body_world_v
  )


__all__ = [
  "StateValidationError",
  "WorldFrameContext",
  "WorldState",
  "hybrid_to_world",
  "world_to_hybrid",
]
